name: Generate Cookiecutter Template

inputs:
  project_name:
    description: 'Project Name'
    required: true
  author:
    description: 'Author'
  email:
    description: 'Email'
  python_version:
    description: 'Project python version'
    default: '3.10'
  output_dir: 
    default: "../"
  # Add more inputs as needed based on your cookiecutter.json

env:
  PYTHON_VERSION: '3.10' # Cookiecutter python version
  TEMP_DIR: temp_cookiecutter_directory # something unique

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Create or switch to 'cookiecutter' branch
      run: |
        git fetch
        if git branch -r | grep -qw "origin/cookiecutter"; then
          echo "Branch exists on remote. Switching to it."
          git checkout cookiecutter
        else
          echo "Branch does not exist. Creating it."
          git checkout -b cookiecutter
          git push -u origin cookiecutter
        fi
      shell: bash

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Cookiecutter
      run: | 
        python3 -m pip install cookiecutter==2.5.0
        python3 -m pip install click==8.1.7
      shell: bash

    - name: Clone template repository for use with cookiecutter
      run: |
        git clone https://github.com/jimmfan/github-actions-cookiecutter-ml.git $TEMP_DIR
      shell: bash

    - name: Generate Project Template
      run: |
        python3 $TEMP_DIR/generate_template.py \
        --project_name="${{ github.event.inputs.project_name }}" \
        --author="${{ github.event.inputs.author }}" \
        --email="${{ github.event.inputs.email }}" \
        --python_version="${{ github.event.inputs.python_version }}" \
        --output_dir="${{ github.event.inputs.output_dir }}"
      shell: bash

    - name: Push Generated Template to Branch
      run: |
        rm -rf $TEMP_DIR
        git status  # Check which files are staged for commit
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'        
        git add -A  # Stage all changes
        git status  # Confirm what's being committed
        git commit -m "Add new project template: ${{ github.event.inputs.project_name }}" || echo "No changes to commit"
        git push origin cookiecutter
      shell: bash