name: Generate Cookiecutter Template

inputs:
  template_path:
    description: 'Template Path'
    required: true
  author:
    description: 'Author'
  email:
    description: 'Email'
  python_version:
    description: 'Project python version'
    default: '3.10'
  output_dir: 
    default: "../"
  # Add more inputs as needed based on your cookiecutter.json

env:
  PYTHON_VERSION: '3.10' # Cookiecutter python version

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Create or switch to 'cookiecutter' branch
      run: |
        git fetch
        if git branch -r | grep -qw "origin/cookiecutter"; then
          echo "Branch exists on remote. Switching to it."
          git checkout cookiecutter
        else
          echo "Branch does not exist. Creating it."
          git checkout -b cookiecutter
          git push -u origin cookiecutter
        fi
      shell: bash

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Cookiecutter and Click
      run: | 
        python3 -m pip install cookiecutter==2.5.0
        python3 -m pip install click==8.1.7
      shell: bash

    - name: Clone template repository for use with cookiecutter
      run: |
        rm -rf .github
        git clone https://github.com/jimmfan/github-actions-cookiecutter-ml.git 
      shell: bash

    - name: list all files
      run: |
        ls
      shell: bash
      continue-on-error: true      

    - name: list all files
      run: |
        ls -R
      shell: bash
      continue-on-error: true

    # - name: list all files
    #   run: |
    #     cat ${{ github.event.inputs.project_name }}/pyproject.toml
    #   shell: bash
    #   continue-on-error: true      

    # - name: list files
    #   run: |
    #     ls 
    #   shell: bash
    #   continue-on-error: true          

    # - name: Cat files 
    #   run: |
    #     cat test_project/pyproject.toml
    #   shell: bash
    #   continue-on-error: true      

    - name: Generate Project Template
      # working-directory: github-actions-cookiecutter-ml
      run: |
        python3 ./github-actions-cookiecutter-ml/generate_template.py \
        --template_path="${{ github.event.inputs.template_path }}" \
        --project_name="${{ github.event.inputs.project_name }}" \
        --author="${{ github.event.inputs.author }}" \
        --email="${{ github.event.inputs.email }}" \
        --python_version="${{ github.event.inputs.python_version }}" \
        --output_dir="${{ github.event.inputs.output_dir }}"
      shell: bash
      continue-on-error: true        

    - name: list all files
      run: |
        ls -R ${{ github.event.inputs.project_name }}
      shell: bash
      continue-on-error: true      

    # - name: Clean and move files
    #   run: |
    #     shopt -s dotglob
    #     mv ${{ github.event.inputs.project_name }}/* .
    #     shopt -u dotglob
    #     rm -rf .github
    #   shell: bash
    #   continue-on-error: true

    - name: Push Generated Template to Branch
      run: |
        git status  # Check which files are staged for commit
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'        
        git add -A  # Stage all changes
        git status  # Confirm what's being committed
        git commit -m "Add new project template: ${{ github.event.inputs.template_path }}" || echo "No changes to commit"
        git push origin cookiecutter
      shell: bash