name: Generate Cookiecutter Template

inputs:
  project_name:
    description: 'Project Name'
    required: true
  author:
    description: 'Author'
    default: 
  email:
    description: 'Email'
  python_version:
    description: 'Project python version'
    default: '3.10'
  # Add more inputs as needed based on your cookiecutter.json

env:
  PYTHON_VERSION: '3.10' # Cookiecutter python version, not the project

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Create or switch to 'cookiecutter' branch
      run: |
        git fetch
        if git branch -r | grep -qw "origin/cookiecutter"; then
          echo "Branch exists on remote. Switching to it."
          git checkout cookiecutter
        else
          echo "Branch does not exist. Creating it."
          git checkout -b cookiecutter
          git push -u origin cookiecutter
        fi
      shell: bash

    - name: Checkout Cookiecutter Branch
      uses: actions/checkout@v3
      with:
        ref: 'cookiecutter'

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Cookiecutter
      run: | 
        python3 -m pip install cookiecutter==2.5.0
        python3 -m pip install click==8.1.7
      shell: bash

    - name: Clone template repository for use with cookiecutter
      run: |
        git clone https://github.com/jimmfan/github-actions-cookiecutter-ml.git ./ml-template
      shell: bash

    - name: list files
      run: |
        ls
        ls ./ml-template

    - name: Generate Project Template
      working-directory: ../  # Sets the working directory for all commands in this step
      run: |
        python3 ./ml-template/generate_template.py \
        --project_name="${{ github.event.inputs.project_name }}" \
        --author="${{ github.event.inputs.author }}" \
        --email="${{ github.event.inputs.email }}" \
        --python_version="${{ github.event.inputs.python_version }}" 
      shell: bash

    - name: Push Generated Template to Branch
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git checkout -b "${{ github.event.inputs.project_name }}-template"
        git add .
        git commit -m "Add new project template: ${{ github.event.inputs.project_name }}"
        git push origin "${{ github.event.inputs.project_name }}-template"
      shell: bash
